## Rebuild the 16ch coherent gzu_5ev design from source in Vivado 2025.1.
## Opens the migrated 2024.1 project, points the IP repo at our ADI library,
## upgrades all IPs to 2025.1, regenerates the bd, and runs synth->impl->bitstream.
set proot /mnt/d/hdl/projects/ad738x_fmc/gzu_5ev/ALERTSPIN0_NUMOFSDI4
set xpr   $proot/ad738x_fmc_gzu_5ev.xpr

## ---- Repackage the custom HLS IP (streamToSteam) to support zynquplus ----
## It was packaged supporting only family 'zynq' (Zynq-7000); 2025.1 enforces
## supported_families strictly -> "unsupported part" lock. The HLS stream-
## converter RTL is family-agnostic, so add zynquplus + re-save (no Vitis HLS).
set hlsxml /mnt/d/hdl/projects/ad738x_fmc/gzu_5ev/hls_ip/streamToSteam/component.xml
ipx::open_ipxact_file $hlsxml
set hcore [ipx::current_core]
puts "REPACKAGE-BEFORE: [get_property supported_families $hcore]"
set_property supported_families {zynq Production zynquplus Production} $hcore
ipx::create_xgui_files $hcore
ipx::update_checksums $hcore
ipx::save_core $hcore
puts "REPACKAGE-AFTER: [get_property supported_families $hcore]"
ipx::unload_core
puts "REPACKAGE-DONE"

open_project $xpr

## Point IP catalog at our packaged ADI library + the custom HLS IP (streamToSteam).
## The .xpr's VM repo paths won't resolve here; without the HLS IP the bd locks.
set_property ip_repo_paths [list /mnt/d/hdl/library /mnt/d/hdl/projects/ad738x_fmc/gzu_5ev/hls_ip] [current_fileset]
update_ip_catalog -rebuild
puts "BUILD: ip_repo_paths = [get_property ip_repo_paths [current_fileset]]"

## Upgrade all 2024.1 IPs to 2025.1
set ips [get_ips]
puts "BUILD: upgrading [llength $ips] IPs to 2025.1 ..."
if {[catch {upgrade_ip $ips} ue]} { puts "BUILD-UPGRADE-WARN: $ue" }

## Confirm nothing is still locked after adding the HLS repo
puts "BUILD: ===== ip_status after upgrade ====="
catch {report_ip_status}
foreach ip [get_ips] { if {[get_property IS_LOCKED $ip]} { puts "BUILD-STILL-LOCKED: $ip" } }

## Regenerate output products for the TOP bd ONLY (nested SmartConnect bds must
## be generated by their parent -- targeting them directly errors with 12-3563).
set bd [get_files $proot/ad738x_fmc_gzu_5ev.srcs/sources_1/bd/system/system.bd]
puts "BUILD: top bd = $bd"
generate_target all $bd
catch {export_ip_user_files -of_objects $bd -no_script -sync -force -quiet}

## Build: synth -> impl -> write_bitstream
reset_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

puts "BUILD-SYNTH-STATUS: [get_property STATUS [get_runs synth_1]]"
puts "BUILD-IMPL-STATUS: [get_property STATUS [get_runs impl_1]]"
puts "BUILD-IMPL-PROGRESS: [get_property PROGRESS [get_runs impl_1]]"
set bit $proot/ad738x_fmc_gzu_5ev.runs/impl_1/system_top.bit
puts "BUILD-BIT: $bit exists=[file exists $bit]"
puts "BUILD-DONE"
exit 0
